# Generated by Django 5.1.2 on 2024-10-22 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieinfo',
            name='year',
            field=models.DateField(default=0),
        ),
    ]
