# Generated by Django 5.1.2 on 2024-10-22 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movieinfo_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieinfo',
            name='year',
            field=models.TextField(),
        ),
    ]
