# Generated by Django 5.1.2 on 2024-10-22 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movieinfo_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieinfo',
            name='summary',
            field=models.TextField(max_length=1000),
        ),
    ]
