# Generated by Django 5.1.2 on 2024-10-26 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_censorinfo_movieinfo_censordetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieinfo',
            name='directedby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='director', to='movies.director'),
        ),
    ]
