# Generated by Django 5.1.2 on 2024-10-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_movieinfo_directedby'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='movieinfo',
            name='acters',
            field=models.ManyToManyField(related_name='acted_movies', to='movies.actor'),
        ),
    ]
